language: groovy
jdk:
- openjdk8
sudo: false
cache:
  directories:
  - "$HOME/.gradle"
before_script:
- rm -rf target
script: "./travis-build.sh"
deploy:
  provider: heroku
  api_key:
    secure: "YYBr1qt5tH/dD7do8qczHTTQB+S39PBGi1I7nxV1+nHl1ZZiejOyCcf9/FzYjEVDOF79nWDHk5LYEH1iaYVk97GPB23ZcmzVt7kirz6rpCoegLiXudLSWRwu+8DsZ86ZJ0Oz30MB8PGJxm8jz4N2Wr/YoNRd6fKtAqERrzkUf6hNVxrFBOQhrSQvgoTtTwgkhvFH1ewUilyDMD5KppssMQiVdYHvAaw5hYjmkX/vekZbMvXlROF11WtfMWb6PqyJIH/Ue0UQBc6v5JhX7ndyxGfKYhSkK3wwIgypDRkMsS4ik84euTcpSi2XIP85jMN6EkWK68ZvBeQ8nykoQVYEk3hMn6qRjeyZt0wtGJ13VaKqEJ9iKG1dA9Esfhu48vfHU3MA/BkCspREQLAVz9Asga4FBD2IuVoLIqB5XvVcVVMGkz9Fkrujv2MIaCU4zRAVhZIj1k2EJ+bsD5GuNAJucPtyE+PxuD3RSWaooHwVg40euuxs26som74BOfkwVG8gbBrlx9Z9pW7tjhYuplcFnxt0KB7KUZBApGlXq/O+skdbX8nMneRjSImPgjn4j6Tzz7v7kfXtIsMjRuE+BVqN9McqQT/XpAWMNzSLPv1/YduJSruyNdoIu47PG54kLn64BrsDAfD6twnSGhld+qAfoqH/TkfGe0r9ECQSpgUTk1c="
